edition = "2018"

#ignore = []

#max_width = 120
#width_heuristics = "Max"
#use_small_heuristics = "Max"

#combine_control_expr = false
#condense_wildcard_suffixes = true
#fn_single_line = true
#imports_layout = "HorizontalVertical"
#match_arm_blocks = false
merge_derives = true
#merge_imports = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
